# frozen_string_literal: true

source "https://rubygems.org"

gem 'cocoapods', :git => 'https://github.com/CocoaPods/CocoaPods.git'

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

# gem "rails"
